# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: weixin

on:
  workflow_dispatch:
  schedule: 
    # 代表国际标准时间23点0分，北京时间需要+8小时，代表北京时间上午7点运行
    - cron: '0 23 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: "3.10"
    - name: Set timezone
      run: |
        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
    - name: install pip package
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: weixin
      run: |
        python3 main.py
